// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiVDKLxZyjwSB9-18B0TgxPFzgHYQljmk',
    appId: '1:613012102212:web:2c4782e08656e7ac377011',
    messagingSenderId: '613012102212',
    projectId: 'sabanciinsight',
    authDomain: 'sabanciinsight.firebaseapp.com',
    storageBucket: 'sabanciinsight.firebasestorage.app',
    measurementId: 'G-611XH1XEB5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnPmvIDxCI5nU85p_TJVOLjptOj9MSa68',
    appId: '1:613012102212:android:d58a91e45b8c3260377011',
    messagingSenderId: '613012102212',
    projectId: 'sabanciinsight',
    storageBucket: 'sabanciinsight.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiVDKLxZyjwSB9-18B0TgxPFzgHYQljmk',
    appId: '1:613012102212:web:7d7a125b814e34bd377011',
    messagingSenderId: '613012102212',
    projectId: 'sabanciinsight',
    authDomain: 'sabanciinsight.firebaseapp.com',
    storageBucket: 'sabanciinsight.firebasestorage.app',
    measurementId: 'G-2X4EM7QXPS',
  );

}